import { Link } from 'react-router-dom';
import Logout from './logout';

const Navbar = () => {
    return ( 
        <nav className="navbar">
            {/* Logo generated by VistaPrint */}
            <img
                src="/transparent-logo.png"
                alt="Logo"
                className="nav-logo"
                style={{ width: 200, height: 50, margin: 0}}
            />

            <div className="links">
                <a href="/">Home</a>
                <Link to="/habitReport">Habit Scorecard</Link>
                <Link to="/finance">Finance</Link>{/* Link to enables us to work with the react router to avoid disturbing the server*/}
                <Link to="/ideas">Ideas</Link>
                <Logout />
            </div>
        </nav>
     );
}
 
export default Navbar;